export const ROUTES = {
  home:           '/',
  login:          '/login',
  signup:         '/signup',
  dashboard:      '/dashboard',
  portfolioInput: '/portfolio/input',
  portfolioList:  '/portfolio/list',
  market:         '/market',
  goals:          '/goals',
  transactions:   '/transactions',
  household:      '/household',
  analysis:       '/analysis',
  ai:             '/ai',
  settings:       '/settings',
} as const
